import streamlit as st, pandas as pd
from google.oauth2 import service_account
from google.cloud import bigquery
from st_aggrid import AgGrid, GridOptionsBuilder, ColumnsAutoSizeMode

credentials = service_account.Credentials.from_service_account_info(
    st.secrets["gcp_service_account"]
)
client = bigquery.Client(credentials=credentials)
# st.set_page_config(layout="wide")
@st.cache_data(ttl=600)



def run_query(query):
    query_job = client.query(query)
    rows_raw = query_job.result()
    rows = [dict(row) for row in rows_raw]
    return rows

q1= st.container(
        width='stretch', 
      height='content', 
      border=True,
      autoscroll=True)
q1.header("Question 1: Top Revenue-Generating Categories")
q1.subheader(body="""
    Join the order_items and products tables to find the total revenue (sum of sale_price) generated by each product category. Only include orders with a status of 'Complete'. Show the category and total_revenue, sorted highest to lowest. Round revenue to 2 decimal places.
            
      💡 Tip: You need to link each sale back to its product to get the category. Use an INNER JOIN on the shared key between order_items and products.

""", anchor=False)

q1_query = run_query("""
                    SELECT category, ROUND(SUM(sale_price), 2) AS Total_Revenue

FROM `bigquery-public-data.thelook_ecommerce.products` AS Products_table
INNER JOIN `bigquery-public-data.thelook_ecommerce.order_items` AS Order_Items_table 

ON Order_Items_table.product_id = Products_table.id
WHERE order_items_table.status = 'Complete'
GROUP BY category
ORDER BY Total_Revenue DESC
                     """ )
q1_query_df = pd.DataFrame(q1_query)
st.image("q1_sql.png", caption='Q1 - SQL Query Results')
st.divider(width='stretch')

st.dataframe(q1_query_df)



q2 = st.container(
    width='stretch', 
    height='content', 
    border=True,
    autoscroll=True,

    )
q2.header('Question 2: Brand Profitability')

q2.subheader("""For each brand, calculate the total profit across all completed orders. Profit per item = sale_price - products.cost. Show the brand, total_profit (rounded to 2 decimal places), and number of completed orders. Sort by total_profit descending. Limit to the top 15 brands.
              
      💡 Tip: You will need to JOIN order_items to products, filter for completed status, then GROUP BY brand with both an aggregate sum and a count.

""")
q2_query = run_query("""
                     SELECT 
  DISTINCT brand, 
  status,
  ROUND(SUM(sale_price - cost),2) Total_Profit, 
  COUNT(Order_Items.id) Total_Orders_Count
FROM `bigquery-public-data.thelook_ecommerce.products` products
JOIN `bigquery-public-data.thelook_ecommerce.order_items` order_Items
  ON order_items.product_id = products.id
WHERE status = 'Complete'
GROUP BY brand, status
ORDER BY Total_Profit DESC""")

st.image('Q2_sql.png', caption='Q2 - SQL Query Results')

q2_query_df = pd.DataFrame(q2_query)
q2_query_df.rename(columns={
    'brand': 'BRAND',
    'status': 'STATUS',
    'Total_Profit': 'TOTAL_PROFIT $ (DESC)',
    'Total_Orders_Count': 'TOTAL_ORDERS_COUNT'
}, inplace=True)
st.dataframe(q2_query_df)


                     
                     

q3 = st.container(
    width='stretch', 
    height='content', 
    autoscroll=True, 
    border=True, 
    )
q3.header('Question 3: Monthly Sales Trend')
q3.subheader(body=''')
Using the order_items table, extract the year and month from created_at and calculate the total number of completed orders per month. Show year, month, and order_count, sorted chronologically. Limit to 2022 onwards.
              
      💡 Tip: BigQuery has date extraction functions. Look up EXTRACT(YEAR FROM col) and EXTRACT(MONTH FROM col). Filter by year using WHERE on the extracted value.

''', anchor=False)

st.image('Q3_sql.png', caption='Q3 - SQL Query Results')


q3_query = run_query("""
                     SELECT 
EXTRACT(YEAR FROM created_at) YEAR, 
EXTRACT(MONTH FROM created_at) MONTH, 
SUM(order_id) order_count,
FROM `bigquery-public-data.thelook_ecommerce.order_items` Order_Items
WHERE EXTRACT(YEAR FROM created_at) > 2022
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
                     """)
q3_df = pd.DataFrame(q3_query)

st.dataframe(q3_df)



Q4 = st.container(width='stretch', height='content', autoscroll=True, border=True)

Q4.header("""Question 4: Fulfillment Center Workload""")
              
Q4.subheader(body='''Join inventory_items to distribution_centers to find out how many inventory units each fulfillment center is responsible for. Show the center name and total_units (count of inventory_items records), sorted from busiest to least busy.

              
      💡 Tip: The join key lives on two different column names in the two tables. Check the schema carefully to match them correctly.

''', anchor=False)

st.image('Q4_sql.png', caption='Q4 - SQL Query Results')

q4_query = run_query("""
                     SELECT DC.name DC_CITY,
COUNT(INV.id) Total_Units 
FROM `bigquery-public-data.thelook_ecommerce.distribution_centers` DC 
JOIN `bigquery-public-data.thelook_ecommerce.inventory_items` INV 
ON INV.product_distribution_center_id = DC.id --both integers
GROUP BY DC_CITY
ORDER BY Total_Units DESC
                     """)
q4_df = pd.DataFrame(q4_query)
q4_df.rename(columns={
    'DC_CITY': 'DISTRIBUTION CENTER - CITY',
    'Total_Units': 'TOTAL_UNITS - DESC'
}, inplace=True)
st.dataframe(q4_df, width='stretch')




Q5 = st.container(width='stretch', height='content', autoscroll=True, border=True)

Q5.header('Question 5: Return Rate by Category')
Q5.subheader('''
Calculate the return rate for each product category: the percentage of order items that have a non-NULL returned_at value. Show category, total_orders, returned_orders, and return_rate (as a percentage rounded to 2 decimal places). Only include categories with more than 50 total orders.

  💡 Tip: You can use a CASE WHEN inside COUNT to count only the rows where a condition is true. Divide by total count and multiply by 100 for the percentage.

''')


Q6 =  st.container(width='content', height='content', autoscroll=True, border=True)
              

              
Q6.header('Q6 - Unsold Inventory')
Q6.subheader(body='''The warehouse team wants to know which products still have units sitting in inventory that have never been sold. Join inventory_items to products and filter for records where sold_at IS NULL. Show the product name, category, brand, and unsold_units (count of unsold records). Sort by unsold_units descending.

     💡 Tip: Filter for NULL in the sold_at column after the JOIN, then GROUP BY product details to count how many unsold units each product has.

''')
st.image('Q6_sql.png', caption='Q6 - SQL Query Results')

q6_query = run_query("""
                     SELECT p.name, p.category, p.brand, COUNT(i.product_id) UNSOLD_UNITS,
FROM `bigquery-public-data.thelook_ecommerce.products` p
JOIN `bigquery-public-data.thelook_ecommerce.inventory_items` i
ON i.product_id = p.id
WHERE(i.sold_at IS NULL)
GROUP BY i.sold_at,p.name,p.category, p.brand
ORDER BY UNSOLD_UNITS DESC
                     """)
q6_df = pd.DataFrame(q6_query)
q6_df.rename(columns={
    'name': 'PRODUCT_NAME',
    'category': 'CATEGORY',
    'brand': 'BRAND',
    'UNSOLD_UNITS': 'UNSOLD_UNITS - DESC'
}, inplace=True)
q6_Aggrid_return = AgGrid(q6_df)


Q7 =  st.container(width='stretch', height='content', autoscroll=False, border=True)
Q7.header('High-Value Completed Orders')
              
Q7.subheader(body='''Find all individual order line items where the sale_price was greater than $150 and the status is 'Complete'. Join to products to include the product name and category. Show order_id, product name, category, sale_price, and the date the order was created (just the date, not the timestamp). Sort by sale_price descending.

   💡 Tip: Use DATE(created_at) to extract just the date portion from a timestamp column. Apply both filters in your WHERE clause using AND.

''')

st.image('Q7_SQL.png', caption='Q7 - SQL Query Results')

q7_query = run_query("""
                     SELECT 
O.order_id, P.name, P.category, O.sale_price, DATE(created_at) Order_Created_At, O.status
FROM `bigquery-public-data.thelook_ecommerce.order_items` O
JOIN `bigquery-public-data.thelook_ecommerce.products` P 
ON O.product_id = P.id
WHERE O.sale_price > 150 AND O.status = 'Complete'
ORDER BY O.sale_price DESC
                     """)
q7_df = pd.DataFrame(q7_query)
q7_df.rename(columns={
    'order_id': 'ORDER_ID',
    'name': 'PRODUCT_NAME',
    'category': 'CATEGORY',
    'sale_price': 'SALE_PRICE - DESC',
    'Order_Created_At': 'ORDER CREATION',
    'status': 'STATUS'
}, inplace=True)
st.dataframe(q7_df)



Q8  = st.container(width='stretch', height='content', autoscroll=True, border=True)

Q8.header('Question 8: Customers Who Returned the Most')

Q8.subheader(body='''Identify the top 10 users with the highest number of returned items. Show the user_id and return_count, sorted from most returns to fewest. Think about what constitutes a 'return' based on the data available to you.

    💡 Tip: A returned item has a non-NULL returned_at value. GROUP BY user_id, COUNT the qualifying rows, and limit to the top 10.

''', anchor=False)

st.image('Q8_SQL.png', caption='Q8 - SQL Query Results')

q8_query = run_query("""
                     SELECT O.user_id, COUNT(O.returned_at) RETURNED_COUNT
FROM `bigquery-public-data.thelook_ecommerce.order_items` O 
WHERE (O.returned_at IS NOT NULL) AND O.status  = 'Returned'
GROUP BY O.user_id
ORDER BY RETURNED_COUNT DESC
LIMIT 10
                     """)
q8_df = pd.DataFrame(q8_query)
q8_df.rename(columns={
    'user_id': 'USER_ID', 
    'RETURNED_COUNT': 'RETURNED_COUNT - DESC'
}, inplace=True)
st.dataframe(q8_df)


q9 = st.container(width='stretch', height='content', autoscroll=True, border=True) 
q9.header('Question 9: Products Never Ordered')

q9.subheader(body='''Use a LEFT JOIN to find products that exist in the products table but have never appeared in order_items. Show the product name, brand, and category. 
             
(Hint: what value would order_items.id have for a product that was never ordered?)
         
💡 Tip: A LEFT JOIN keeps all rows from the left table even when there is no match in the right. After the join, filter for rows where the right side's key is NULL.

''')
st.image('Q9_SQL.png', caption='Q9 - SQL Query Results')
st.divider(width='stretch')
q9_query = run_query("""
                     SELECT P.name, P.brand, P.category, 
FROM `bigquery-public-data.thelook_ecommerce.products` P
LEFT JOIN `bigquery-public-data.thelook_ecommerce.order_items` O 
ON P.id = O.product_id
WHERE O.product_id IS NULL
                     """)
q9_df = pd.DataFrame(q9_query)
q9_df.rename(columns={
    'name': 'UNORDERED PRODUCT ITEMS',
    'brand': 'BRAND',
    'category': 'CATEGORY'

}, inplace=True)
q9_df_Aggrid_return = AgGrid(q9_df)

st.divider(width='stretch')

Q10 = st.container(width='stretch', height='content', autoscroll=True, border=True)
Q10.header('Question 10: Revenue vs. Cost by Distribution Center')
         
Q10.subheader(body = '''For each distribution center, calculate the total revenue generated from completed sales and the total cost of the inventory sold. Show the center name, total_revenue, total_cost, and gross_profit (revenue minus cost), sorted by gross_profit descending. You will need to join three tables: order_items, inventory_items, and distribution_centers.
         
      💡 Tip: This is a multi-table join. Sketch out which key connects each pair of tables before writing the query. Build and test one JOIN at a time.

''')

st.divider(width='stretch')
